### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-jtnr7#3]
Cool! Now, It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data.
Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by davidfers** [comment]
Fixed with the placeholder[
![Screenshot from 2022-08-08 20-59-14](https://user-images.githubusercontent.com/60383773/183493698-5c1dcb81-ac37-461a-a258-d90d941c74bf.png)

**Comment by davidfers** [comment]
done
